package com.rules

import com.paper.ssm.entity.*
import java.util.*

global LinkedHashMap featureList;

//declare Conclusion
////    熔化效率
//    meltingEfficiency: Float
////    焦炭反应性
//    cokeReactivity: Float
//end

rule A
    when
        $dsp: DataScene(title == "铸铁-铸钢-有色金属-湿砂型铸造(静压KW线)-熔炼" && category == "湿砂型")
        (DeviceData(device.usage == "中频电炉") from $dsp.deviceDataList)
    then
        Conclusion conclusion = new Conclusion();
        conclusion.setMeltingEfficiency(0.55f);
        conclusion.setCokeReactivity(0.55f);
        insert(conclusion);
    end
rule B
    when
//        $dsp: DataScene()
//        (EnergyData(energy.title == "天然气") from $dsp.energyDataList)
        Conclusion(cokeReactivity > 0.5 && cokeReactivity < 0.6)
    then
        String[] datas = {"废钢消耗","生铁消耗","焦炭消耗"};
        ArrayList<String> arrayList0 = new ArrayList<>();
        arrayList0.add(datas[0]);
        arrayList0.add(datas[1]);
        arrayList0.add(datas[2]);
        arrayList0.add("炉料总量");
        featureList.put(arrayList0,"add");
        ArrayList<String> arrayList1 = new ArrayList<>();
        arrayList1.clear();
        arrayList1.add(datas[2]);
        arrayList1.add(datas[0]);
        arrayList1.add("焦钢比");
        featureList.put(arrayList1,"div");
        ArrayList<String> arrayList2 = new ArrayList<>();
        arrayList2.add(datas[2]);
        arrayList2.add(datas[1]);
        arrayList2.add("焦铁比");
        featureList.put(arrayList2,"div");
    end
rule C
    when
        Conclusion(meltingEfficiency > 0.5 && meltingEfficiency < 0.6)
    then
        System.out.println("ok");
    end


//rule D
//    when
//        $dataScene: DataScene(title == "")
//    then
//
//    end
//rule E
//    when
//        $dataScene: DataScene(title == "")
//    then
//
//    end

