package com.rules

import com.paper.ssm.entity.*
import java.util.*
import org.mvel2.util.Make

global java.util.List featureList;
//declare Conclusion
////    熔化效率
//    meltingEfficiency: Float
////    焦炭反应性
//    cokeReactivity: Float
//end

rule A
    when
        $dsp: DataScene(title == "铸铁-铸钢-有色金属-湿砂型铸造(静压KW线)-熔炼" && category == "湿砂型")
        (DeviceData(device.usage=="中频电炉") from $dsp.deviceDataList)
    then
        Conclusion conclusion = new Conclusion();
        conclusion.setMeltingEfficiency(0.55f);
        conclusion.setCokeReactivity(0.55f);
        insert(conclusion);
    end
rule B
    when
//        $dsp: DataScene()
//        (EnergyData(energy.title == "天然气") from $dsp.energyDataList)
        Conclusion(cokeReactivity > 0.5 && cokeReactivity < 0.6)
    then
        String[] datas = {"废钢消耗","生铁消耗","焦炭消耗"};
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add(datas[0]);
        arrayList.add(datas[1]);
        arrayList.add(datas[2]);
        HashMap<ArrayList<String>,String> hashMap = new HashMap<>();
        hashMap.put(arrayList,"add");
        featureList.add(hashMap);
        arrayList.clear();
        hashMap.clear();
        arrayList.add(datas[2]);
        arrayList.add(datas[0]);
        hashMap.put(arrayList,"div");
        arrayList.clear();
        hashMap.clear();
        arrayList.add(datas[2]);
        arrayList.add(datas[1]);
        hashMap.put(arrayList,"div");
        featureList.add(hashMap);
    end
rule C
    when
        Conclusion(meltingEfficiency > 0.5 && meltingEfficiency < 0.6)
    then
        System.out.println("ok");
    end


//rule D
//    when
//        $dataScene: DataScene(title == "")
//    then
//
//    end
//rule E
//    when
//        $dataScene: DataScene(title == "")
//    then
//
//    end

